version: "3"

services:
  app:
    build:
      args:
        user: vscode
        uid: 1000
      context: ./
      dockerfile: docker/devcontainer/Dockerfile
    working_dir: /app
    volumes: 
      - "./:/app"